### ISSUE TITLE
letsencrypt doesn't autorenew

### ISSUE THREAD

**Issue by db0** [loomio/loomio-deploy#42]
I managed to set up a loomio installation for myself on my VPS very easily, but after a few months my letsencrypt certificate expired and I've been trying unsuccessfully to renew it since.

(A main problem is that I'm not quite that familiar with docker)

I'm seeing this message constantly in the logs

```
loomio-letsencrypt | /etc/nginx/certs/loomio.dbzer0.com /app
loomio-letsencrypt | Creating/renewal loomio.dbzer0.com certificates... (loomio.dbzer0.com)
loomio-letsencrypt | 2019-03-19 09:55:14,671:INFO:simp_le:1479: Generating new certificate private key
loomio-letsencrypt | 2019-03-19 09:55:16,898:ERROR:simp_le:1446: CA marked some of the authorizations as invalid, which likely means it could not access http://example.com/.well-known/acme-challenge/X. Did you set correct path in -d example.com:path or --default_root? Are all your domains accessible from the internet? Please check your domains' DNS entries, your host's network/firewall setup and your webserver config. If a domain's DNS entry has both A and AAAA fields set up, some CAs such as Let's Encrypt will perform the challenge validation over IPv6. If your DNS provider does not answer correctly to CAA records request, Let's Encrypt won't issue a certificate for your domain (see https://letsencrypt.org/docs/caa/). Failing authorizations: https://acme-v01.api.letsencrypt.org/acme/authz/1X8LZlnKydfHIwbo1GjDr12_Uuu9NY8bWPaLF1vwctA
loomio-letsencrypt | Traceback (most recent call last):
loomio-letsencrypt |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1583, in main
loomio-letsencrypt |     return main_with_exceptions(cli_args)
loomio-letsencrypt |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1567, in main_with_exceptions
loomio-letsencrypt |     persist_new_data(args, existing_data)
loomio-letsencrypt |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1489, in persist_new_data
loomio-letsencrypt |     account_key=client.key, key=None, cert=None, chain=None))
loomio-letsencrypt |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 1195, in persist_data
loomio-letsencrypt |     plugin.save(new_data)
loomio-letsencrypt |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 493, in save
loomio-letsencrypt |     key = self.dump_key(data.key)
loomio-letsencrypt |   File "/usr/lib/python2.7/site-packages/simp_le.py", line 436, in dump_key
loomio-letsencrypt |     return OpenSSL.crypto.dump_privatekey(self.typ, data.wrapped).strip()
loomio-letsencrypt | AttributeError: 'NoneType' object has no attribute 'wrapped'
loomio-letsencrypt | 
loomio-letsencrypt | Unhandled error has happened, traceback is above
loomio-letsencrypt | 
loomio-letsencrypt | Debugging tips: -v improves output verbosity. Help is available under --help.
loomio-letsencrypt | /app
loomio-letsencrypt | Sleep for 3600s
```
It seems like the letsencrypt process is having trouble accessing my own site's challenge, but I don't understand how the process is working exactly and google searches were not really pointing me out in the right direction.

What I suspect is that this is caused because loomio for some reason is listening only on tcp6 and not at all in tcp4.

```
# netstat -aN | grep -e https -e 8000
tcp6       0      0 :::https                :::*                    LISTEN     
tcp6       0      0 :::8000                 :::*                    LISTEN  
```
I don't know why it defaults like that or how to modify that though. I use port 8000 instead of 80 because I'm also running an apache installation in the same host.

Thanks for the help

**Comment by db0** [comment]
So it turns out that if I disable my apache and set the loomio port to 80 and restart it, the letsencrypt renewal works correctly. It seems it cannot handle a different port.

**Comment by robguthrie** [comment]
Yea, let's encrypt needs 80 to get started.

Sorry I wasn't able help more quickly.

**Comment by db0** [comment]
Cool. Maybe add a note to the readme about that too.
