### ISSUE TITLE
contact_messages doesn't work

### ISSUE THREAD

**Issue by yagilm** [loomio/loomio-deploy#66]
Here are the logs:
```
loomio-app     | source=rack-timeout id=e16f8c18-eb77-4e3c-a48f-797f6e86d684 timeout=15000ms state=ready
loomio-app     | Started POST "/api/v1/contact_messages" for <<redacted>> at 2020-04-12 11:21:51 +0000
loomio-app     | Processing by API::ContactMessagesController#create as JSON
loomio-app     |   Parameters: {"contact_message"=>{"email"=>"manos@<<redacted>>", "subject"=>"i wnat to test that the send message works", "user_id"=>2, "message"=>"This is a test, yes", "name"=>"manos"}}
loomio-app     | Completed 500 Internal Server Error in 19ms (ActiveRecord: 1.9ms)
loomio-app     |   
loomio-app     | Addressable::URI::InvalidURIError (Invalid port number: "80api"):
loomio-app     |   
loomio-app     | app/extras/clients/request.rb:17:in `response'
loomio-app     | app/extras/clients/request.rb:12:in `perform!'
loomio-app     | app/extras/clients/base.rb:55:in `block in perform'
loomio-app     | app/extras/clients/base.rb:55:in `tap'
loomio-app     | app/extras/clients/base.rb:55:in `perform'
loomio-app     | app/extras/clients/base.rb:22:in `post'
loomio-app     | app/extras/clients/os_ticket.rb:3:in `post_message'
loomio-app     | app/models/contact_message.rb:13:in `save'
loomio-app     | app/services/contact_message_service.rb:3:in `create'
loomio-app     | app/controllers/api/restful_controller.rb:28:in `create_action'
loomio-app     | app/controllers/api/snorlax_base.rb:18:in `create'
loomio-app     | app/helpers/locales_helper.rb:8:in `use_preferred_locale'
loomio-app     | source=rack-timeout id=e16f8c18-eb77-4e3c-a48f-797f6e86d684 timeout=15000ms service=39ms state=completed
loomio-nginx   | nginx.1    | <<redacted>> <<redacted>> - - [12/Apr/2020:11:21:51 +0000] "POST /api/v1/contact_messages HTTP/2.0" 500 69 "https://<<redacted>>/contact" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:72.0) Gecko/20100101 Firefox/72.0"
```

**Comment by robguthrie** [comment]
Sorry about this. The contact messages system was not really intended to be used by open source installs. It's written to connect to OSTicket only, rather than to send an email to the administrator. I'll make it a ENV flag to enable it , so that it's off by default.
