### ISSUE TITLE
Wrong version number (Worker)

### ISSUE THREAD

**Issue by mishali8** [loomio/loomio-deploy#67]
Hi Guys,
I tried to install loomio-deploy as is and I see two problems:
1. problem with letsencrypt, and I fix it with manually created a cert and key.
2. its issue with Worker, its not working well and I get error : OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: wrong version number
after that I got a lot of errors from Ruby and gems.

also, I cant send emails with my email account in office365 and from my Gmail, I tried any port but the only error I got is regarding OpenSSL.

Need your help to finish the installation, it's not must be docker BTW.

**Comment by robguthrie** [comment]
I don't know how to help you given the information you have provided.

It sounds like you have one error, sending emails generates an OpenSSL error? Sounds like your SMTP is not configured correctly.

Please put more effort into sharing the relevant information if you want me to help you for free.

**Comment by mishali8** [comment]
Thank you for your answer.
please see information:
env email information:
SMTP_AUTH=plain
SMTP_DOMAIN=gmail.com
SMTP_SERVER=smtp.gmail.com
SMTP_PORT=587
SMTP_USERNAME=<my gmail email ####@gmail.com>
SMTP_PASSWORD=<mypassword>
SMTP_USE_SSL=1

I checked open port and it looks good:
telnet smtp.gmail.com 587
Trying 209.85.203.109...
Connected to smtp.gmail.com.

Errors I got immediately after running docker:
1.
loomio-nginx | dockergen.1 | 2020/04/26 06:31:16 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'

2. 
loomio-nginx | nginx.1    | 2020/04/26 06:33:09 [error] 32#32: *97 connect() failed (111: Connection refused) while connecting to upstream, client: 77.127.79.116, server: vote.kol.one, request: "GET /cable HTTP/1.1", upstream: "http://172.17.0.5:3000/cable", host: "vote.kol.one"

3. (same error I got after trying to send email by sign in)
loomio-worker | 2020-04-26T06:21:40.403Z pid=8 tid=gsm492ets WARN: {"context":"Job raised exception","job":{"retry":true,"queue":"login_emails","backtrace":true,"class":"Sidekiq::Extensions::DelayedMailer","args":["---\n- !ruby/class 'UserMailer'\n- :login\n- - 2\n  - 62\n"],"jid":"379943bd525b12ccf41785c8","created_at":1587851591.298789,"enqueued_at":1587882097.603346,"error_message":"SSL_connect returned=1 errno=0 state=error: wrong version number","error_class":"OpenSSL::SSL::SSLError","failed_at":1587851600.580349,"retry_count":5,"error_backtrace":"eJzNWNFy2jAQ/JU0L2lnioVlbCC/0umosn0BN7LkSjIkf19ZEolNE8BYyfQN\nZGv3dLfaO/hxi1olERMFZYhVOZJt/oxwlEVzxEGjRgotCsEimd8vFvcVv/lV\nCM6h0IQLnpt9j3e338eDKMWIMptBE493HkbVuukg0pXD0EyN35tiu7cURGkq\nx+yMVy7yN7blLS8ZoA3UCtW0YjMcLaPYonVfO5y9kI+oBFbtQD6TGvRWlOoF\nPJ6vX8FJt0oUKFUJHp5p7hLgXvgyEr82UdENdEg4TteHXB7oJqBlLi4rqRvz\nyUOeQKSFNgnqgEDO0ghHiUV2y8Sto5wqi5++g2/fO0OyA9U2jZD6iGUHxD9A\nXOjqoSpoR61snrPVkK/iSsu2Bn5KPNewoVdkkDaViWX+MML+8S4mubxQ6aov\n0HP1uVBWgdTkkV/0blMRL95WFhf7qXwSVNHSnNmzxEvLs6UdCIGnAhpbj485\nVDKowumzqKqEx+rPzHhmtLQMfgXBkwaurEwHpD2dNiAfhKyvgjedpTDRC4sX\nrzMLCE9QtBrIb5EHAM361f2KbxjsgKlvXaH9i1eR1FVp3tpTCajY0opbruQf\nz9iJRziBz2EvTYUKIpvakMRzw5NkC8tknhH7EJnict2zCXuND5F0xAke8hqa\nU3duCqvp2FoKZiRAjh7ZQJZZXxPEa2Zf6S15YdWSFp+QFOyKcSYXIyu8mI+s\nsDKhyeeZpDvgxufixIwldkrpFkz4GjbS94Fe7Ov/IvSR+Ie2dTXs0cVNhvFO\nua1D5CTrW0LWt4SyUg3VxfYqFmNYRpz64MCxZbEAIYJO+0GnwYKWxs/tSLBI\nRpnIhZOHM3NrApI2jescK9cJu5XpDMYOBC0d8PLoDGEYPvkM+BLgSwqKp7nI\nkf7ivv4WwfQ3YMHp8vA7Soe46Xhw05OgN52JzQZ8bkImGqfvDizh3GnpmuOG\niTyIO+HjGXpKpL3Mup7VzQ8B6pT4gVVCY1pXiFP7ITuY/uMM+xAD9TpfZ79G\nBA9wbP/TUban/tx4H8s4qf0nKXY633eZK8VmEtax/BR9AKK3Emh5d/vzL2Y/\nr0c=\n","retried_at":1587852274.031893},"jobstr":"{\"retry\":true,\"queue\":\"login_emails\",\"backtrace\":true,\"class\":\"Sidekiq::Extensions::DelayedMailer\",\"args\":[\"---\\n- !ruby/class 'UserMailer'\\n- :login\\n- - 2\\n  - 62\\n\"],\"jid\":\"379943bd525b12ccf41785c8\",\"created_at\":1587851591.298789,\"enqueued_at\":1587882097.603346,\"error_message\":\"SSL_connect returned=1 errno=0 state=error: wrong version number\",\"error_class\":\"OpenSSL::SSL::SSLError\",\"failed_at\":1587851600.580349,\"retry_count\":5,\"error_backtrace\":\"eJzNWNFy2jAQ/JU0L2lnioVlbCC/0umosn0BN7LkSjIkf19ZEolNE8BYyfQN\\nZGv3dLfaO/hxi1olERMFZYhVOZJt/oxwlEVzxEGjRgotCsEimd8vFvcVv/lV\\nCM6h0IQLnpt9j3e338eDKMWIMptBE493HkbVuukg0pXD0EyN35tiu7cURGkq\\nx+yMVy7yN7blLS8ZoA3UCtW0YjMcLaPYonVfO5y9kI+oBFbtQD6TGvRWlOoF\\nPJ6vX8FJt0oUKFUJHp5p7hLgXvgyEr82UdENdEg4TteHXB7oJqBlLi4rqRvz\\nyUOeQKSFNgnqgEDO0ghHiUV2y8Sto5wqi5++g2/fO0OyA9U2jZD6iGUHxD9A\\nXOjqoSpoR61snrPVkK/iSsu2Bn5KPNewoVdkkDaViWX+MML+8S4mubxQ6aov\\n0HP1uVBWgdTkkV/0blMRL95WFhf7qXwSVNHSnNmzxEvLs6UdCIGnAhpbj485\\nVDKowumzqKqEx+rPzHhmtLQMfgXBkwaurEwHpD2dNiAfhKyvgjedpTDRC4sX\\nrzMLCE9QtBrIb5EHAM361f2KbxjsgKlvXaH9i1eR1FVp3tpTCajY0opbruQf\\nz9iJRziBz2EvTYUKIpvakMRzw5NkC8tknhH7EJnict2zCXuND5F0xAke8hqa\\nU3duCqvp2FoKZiRAjh7ZQJZZXxPEa2Zf6S15YdWSFp+QFOyKcSYXIyu8mI+s\\nsDKhyeeZpDvgxufixIwldkrpFkz4GjbS94Fe7Ov/IvSR+Ie2dTXs0cVNhvFO\\nua1D5CTrW0LWt4SyUg3VxfYqFmNYRpz64MCxZbEAIYJO+0GnwYKWxs/tSLBI\\nRpnIhZOHM3NrApI2jescK9cJu5XpDMYOBC0d8PLoDGEYPvkM+BLgSwqKp7nI\\nkf7ivv4WwfQ3YMHp8vA7Soe46Xhw05OgN52JzQZ8bkImGqfvDizh3GnpmuOG\\niTyIO+HjGXpKpL3Mup7VzQ8B6pT4gVVCY1pXiFP7ITuY/uMM+xAD9TpfZ79G\\nBA9wbP/TUban/tx4H8s4qf0nKXY633eZK8VmEtax/BR9AKK3Emh5d/vzL2Y/\\nr0c=\\n\",\"retried_at\":1587852274.031893}"}
loomio-worker | 2020-04-26T06:21:40.403Z pid=8 tid=gsm492ets WARN: OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: wrong version number
loomio-worker | 2020-04-26T06:21:40.403Z pid=8 tid=gsm492ets WARN: /usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock'
loomio-worker | /usr/local/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
loomio-worker | /usr/local/lib/ruby/2.6.0/net/smtp.rb:584:in `tlsconnect'
loomio-worker | /usr/local/lib/ruby/2.6.0/net/smtp.rb:552:in `do_start'
loomio-worker | /usr/local/lib/ruby/2.6.0/net/smtp.rb:518:in `start'
loomio-worker | /usr/local/bundle/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
loomio-worker | /usr/local/bundle/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
loomio-worker | /usr/local/bundle/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
loomio-worker | /usr/local/bundle/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
loomio-worker | /usr/local/bundle/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:560:in `block in deliver_mail'
loomio-worker | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
loomio-worker | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
loomio-worker | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
loomio-worker | /usr/local/bundle/gems/actionmailer-5.2.3/lib/action_mailer/base.rb:558:in `deliver_mail'
loomio-worker | /usr/local/bundle/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
loomio-worker | /usr/local/bundle/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:114:in `block in deliver_now'
loomio-worker | /usr/local/bundle/gems/actionmailer-5.2.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
loomio-worker | /usr/local/bundle/gems/actionmailer-5.2.3/lib/action_mailer/message_delivery.rb:113:in `deliver_now'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/extensions/action_mailer.rb:23:in `perform'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:196:in `execute_job'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
loomio-worker | /usr/local/bundle/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/sidekiq.rb:32:in `block in call'
loomio-worker | /usr/local/bundle/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:376:in `perform_action_with_newrelic_trace'
loomio-worker | /usr/local/bundle/gems/newrelic_rpm-6.10.0.364/lib/new_relic/agent/instrumentation/sidekiq.rb:28:in `call'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
loomio-worker | /usr/local/bundle/gems/sentry-raven-2.13.0/lib/raven/integrations/sidekiq.rb:9:in `call'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/middleware/chain.rb:143:in `invoke'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:163:in `block in process'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/job_retry.rb:111:in `local'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/rails.rb:43:in `block in call'
loomio-worker | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
loomio-worker | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/reloader.rb:73:in `block in wrap'
loomio-worker | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/execution_wrapper.rb:87:in `wrap'
loomio-worker | /usr/local/bundle/gems/activesupport-5.2.3/lib/active_support/reloader.rb:72:in `wrap'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/rails.rb:42:in `call'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:257:in `stats'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/job_logger.rb:13:in `call'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/job_retry.rb:78:in `global'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:124:in `block in dispatch'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/logger.rb:10:in `with'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/job_logger.rb:33:in `prepare'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:123:in `dispatch'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:162:in `process'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:78:in `process_one'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/processor.rb:68:in `run'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/util.rb:15:in `watchdog'
loomio-worker | /usr/local/bundle/gems/sidekiq-6.0.7/lib/sidekiq/util.rb:24:in `block in safe_thread'
loomio-worker | 2020-04-26T06:21:40.404Z pid=8 tid=gsm492d44 class=Sidekiq::Extensions::DelayedMailer jid=dc7a6f106fcd661f1c1c3f5a elapsed=2.788 INFO: fail


Thank you

**Comment by marvinroman** [comment]
Any luck in resolving this? 

I am having the same issue, except I am using a mailserver I run myself. I have never had any issues connecting with any mail client to the server, but receiving the same error as you with Rails. I have done SMTP verification using multiple services like MX Toolbox & Immuniweb. 

Essentially what I understand the error to mean is that Rails SSL versions are not not supported on my server. My server runs TLSv.1.2 & TLSv1.3. 

Do you know where in the Rails configuration settings we can adjust TLS versions? Could it be possible that it still utilizes what are considered insecure SSL versions?

**Comment by robguthrie** [comment]
I'm really sorry I've not been able to help - I just don't have a clue, and I've got no time to debug this as I'm working on important new features.

As you can see in the source code, we don't actually handle sending email ourselves.
It's Rails - ActionMailer,  and we just pass the ENV settings through as normal in config/application.rb

For reference, we use Amazson SES just fine

**Comment by lastCent** [comment]
I had the exact same issue. It occurred when trying to set up SMTP to a host which does not support SSL. 
Setting SMTP_USE_SSL=0 did not seem to prevent Loomio from trying to connect using SSL, however commenting the line out completely worked.

**Comment by robguthrie** [comment]
yes, 0 is a true value in ruby, do I need to tell people to comment lines out rather than set a value?

**Comment by lastCent** [comment]
Ah, well this is embarrassing. As you can tell I have no ruby background, so for the likes of me, who just want to get Loomio running, it would be helpful to include a small notice yes.
