### ISSUE TITLE
Getting SSL error on fresh loomio install

### ISSUE THREAD

**Issue by Smona** [loomio/loomio-deploy#7]
I followed the guide in the readme to set up a loomio deploy but I'm getting the following error:
```
loomio_1      | Started DELETE "/api/v1/sessions/" for 173.174.95.141 at 2017-01-20 03:13:32 +0000
loomio_1      | Processing by API::SessionsController#destroy as JSON
loomio_1      | Completed 500 Internal Server Error in 75ms (ActiveRecord: 2.2ms)
loomio_1      |
loomio_1      | OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert internal error):
loomio_1      |   app/services/message_channel_service.rb:16:in `publish'
loomio_1      |   app/controllers/api/sessions_controller.rb:18:in `destroy'
loomio_1      |   app/controllers/application_controller.rb:83:in `user_time_zone'
```

I have been trying to figure out how to fix this issue but I'm not well-versed in SSL. Any help would be greatly appreciated.

**Comment by robguthrie** [comment]
Hi Smona,

Can you give me an indication of how broken things are with this behaviour?
Seems like the Faye server is not... working correctly.

Is this a new installation?

**Comment by Smona** [comment]
Yes, this is a fresh installation on an Ubuntu 14.04 x64 Digital Ocean droplet. 

I ran into the bug attempting to use the "sign out" button so I could test email functionality with a password reset. Button is nonfunctional and the server gives me that error. I get an SSL error in my developer console when I load the dashboard but it shows up fine. I haven't tested any other features yet but I can if it would be helpful

**Comment by robguthrie** [comment]
Can you post through logs from your Faye server?

From what I can see, the system is erroring when trying to send a message to Faye, the system that keeps open sessions updated via websockets.

It seems like there is something wrong with the SSl certificates.

try `docker-compose logs` for more detail.

**Comment by Smona** [comment]
So for starters, here's the output when sending a password reset email:

```
loomio_1      | Started GET "/users/password/new" for 173.245.50.168 at 2017-01-26 03:20:36 +0000
loomio_1      | Processing by Devise::PasswordsController#new as HTML
loomio_1      |   Rendered devise/passwords/new.html.haml within layouts/application (49.8ms)
loomio_1      |   Rendered application/_social_metadata.html.haml (11.8ms)
loomio_1      |   Rendered application/_google_analytics.html.haml (0.3ms)
loomio_1      |   Rendered application/_flash_messages.html.haml (0.2ms)
loomio_1      |   Rendered application/_footer.html.haml (1.0ms)
loomio_1      | Completed 200 OK in 91ms (Views: 74.2ms | ActiveRecord: 0.0ms)
nginx_1       | nginx.1    | loomio.political-revolution.com 173.245.50.168 - - [26/Jan/2017:03:20:37 +0000] "GET /users/password/new HTTP/1.1" 200 4545 "https://loomio.political-revolution.com/users/sign_in" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 YaBrowser/17.1.0.1974 Yowser/2.5 Safari/537.36"
db_1          | ERROR:  duplicate key value violates unique constraint "visits_pkey"
db_1          | DETAIL:  Key (id)=(264afb9a-5297-49df-ab56-b11feea38a03) already exists.
db_1          | STATEMENT:  INSERT INTO "visits" ("id", "visitor_id", "started_at", "ip", "user_agent", "referrer", "landing_page", "screen_height", "screen_width", "referring_domain", "browser", "os", "device_type") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13) RETURNING "id"
nginx_1       | nginx.1    | loomio.political-revolution.com 173.245.50.168 - - [26/Jan/2017:03:20:38 +0000] "POST /ahoy/visits HTTP/1.1" 200 122 "https://loomio.political-revolution.com/users/password/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 YaBrowser/17.1.0.1974 Yowser/2.5 Safari/537.36"
nginx_1       | nginx.1    | loomio.political-revolution.com 173.245.50.168 - - [26/Jan/2017:03:20:39 +0000] "POST /ahoy/events HTTP/1.1" 200 39 "https://loomio.political-revolution.com/users/password/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 YaBrowser/17.1.0.1974 Yowser/2.5 Safari/537.36"
loomio_1      | Started POST "/users/password" for 173.245.50.168 at 2017-01-26 03:20:46 +0000
loomio_1      | Processing by Devise::PasswordsController#create as HTML
loomio_1      |   Parameters: {"utf8"=>"✓", "authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"mason.bourgeois@gmail.com"}, "commit"=>"Send me reset password instructions"}
loomio_1      |   Rendered devise/mailer/reset_password_instructions.html.haml within layouts/base_mailer (30.5ms)
loomio_1      |   Rendered devise/mailer/reset_password_instructions.text.haml within layouts/base_mailer (6.3ms)
nginx_1       | nginx.1    | 2017/01/26 03:21:46 [error] 38#38: *669 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 173.245.50.168, server: loomio.political-revolution.com, request: "POST /users/password HTTP/1.1", upstream: "http://172.17.0.5:3000/users/password", host: "loomio.political-revolution.com", referrer: "https://loomio.political-revolution.com/users/password/new"
nginx_1       | nginx.1    | loomio.political-revolution.com 173.245.50.168 - - [26/Jan/2017:03:21:46 +0000] "POST /users/password HTTP/1.1" 504 585 "https://loomio.political-revolution.com/users/password/new" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 YaBrowser/17.1.0.1974 Yowser/2.5 Safari/537.36"
loomio_1      |
loomio_1      | Sent mail to mason.bourgeois@gmail.com (59881.0ms)
loomio_1      | Completed 500 Internal Server Error in 60124ms (ActiveRecord: 13.3ms)
loomio_1      |
loomio_1      | EOFError (end of file reached):
```

**Comment by robguthrie** [comment]
Erroring when resetting password usually means you have an SMTP configuration problem. Have you configured your SMTP correctly?
