### ISSUE TITLE
Postgres connection error

### ISSUE THREAD

**Issue by dariusk** [loomio/loomio-deploy#86]
Hi. I'm trying to run an instance of Loomio on a clean Ubuntu 21.10 server and I'm running into the issue where it can't connect to Postgres. In the other issues about this (#69, #71) the suggested solution is to update `docker-compose` but I'm already up-to-date with `master`, as I just cloned the repo.

I've attached the output here -- I'm following the README to the letter, so this is right after the `docker-compose up -d db` step, which seemed to run just fine. Any ideas?

```
$ docker-compose run app rake db:setup
Creating loomio-redis ... done
Creating loomio-deploy_app_run ... done
/loomio/config/initializers/sidekiq.rb:2: warning: Sidekiq's Delayed Extensions will be removed in Sid
ekiq 7.0
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disabl
e this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` i
nstead.


rake aborted!
ActiveRecord::ConnectionNotEstablished: could not connect to server: Connection timed out
        Is the server running on host "172.20.0.2" and accepting
        TCP/IP connections on port 5432?
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_handling.rb:283:in `connection'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/model_schema.rb:380:in `table_exists?'
/usr/local/bundle/bundler/gems/custom_counter_cache-7a4ed2c70c6a/lib/custom_counter_cache/model.rb:46:in `update_counter_cache'
/loomio/app/models/membership.rb:51:in `<class:Membership>'
/loomio/app/models/membership.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:424:in `block in require_or_load'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:39:in `block in load_interlock'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies/interlock.rb:13:in `loading'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:39:in `load_interlock'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:402:in `require_or_load'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:558:in `load_missing_constant'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:213:in `const_missing'
/loomio/lib/plugins/module_const_missing.rb:4:in `const_missing'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:595:in `load_missing_constant'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:213:in `const_missing'
/loomio/lib/plugins/module_const_missing.rb:4:in `const_missing'
/loomio/app/helpers/error_rescue_helper.rb:15:in `included'
/loomio/app/controllers/application_controller.rb:4:in `include'
/loomio/app/controllers/application_controller.rb:4:in `<class:ApplicationController>'
/loomio/app/controllers/application_controller.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:424:in `block in require_or_load'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:39:in `block in load_interlock'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies/interlock.rb:13:in `loading'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:39:in `load_interlock'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:402:in `require_or_load'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:558:in `load_missing_constant'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:213:in `const_missing'
/loomio/lib/plugins/module_const_missing.rb:4:in `const_missing'
/usr/local/bundle/gems/inherited_resources-1.13.1/app/controllers/inherited_resources/base.rb:11:in `<module:InheritedResources>'
/usr/local/bundle/gems/inherited_resources-1.13.1/app/controllers/inherited_resources/base.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:424:in `block in require_or_load'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:39:in `block in load_interlock'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies/interlock.rb:13:in `loading'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:39:in `load_interlock'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:402:in `require_or_load'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:558:in `load_missing_constant'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:213:in `const_missing'
/loomio/lib/plugins/module_const_missing.rb:4:in `const_missing'
/usr/local/bundle/gems/activeadmin-2.10.0/lib/active_admin/base_controller/authorization.rb:3:in `<module:ActiveAdmin>'
/usr/local/bundle/gems/activeadmin-2.10.0/lib/active_admin/base_controller/authorization.rb:2:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/activeadmin-2.10.0/lib/active_admin/base_controller.rb:2:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/activeadmin-2.10.0/lib/active_admin/resource_controller/action_builder.rb:3:in `<module:ActiveAdmin>'
/usr/local/bundle/gems/activeadmin-2.10.0/lib/active_admin/resource_controller/action_builder.rb:2:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/activeadmin-2.10.0/lib/active_admin/resource_controller.rb:3:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/activeadmin-2.10.0/lib/active_admin/batch_actions.rb:8:in `block in <main>'
/usr/local/bundle/gems/activeadmin-2.10.0/lib/active_admin.rb:116:in `block in wrap_block_for_active_support_notifications'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/notifications/fanout.rb:186:in `finish'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/notifications/fanout.rb:63:in `block in finish'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/notifications/fanout.rb:63:in `each'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/notifications/fanout.rb:63:in `finish'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/notifications/instrumenter.rb:45:in `finish_with_state'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/notifications/instrumenter.rb:30:in `instrument'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/notifications.rb:203:in `instrument'
/usr/local/bundle/gems/activeadmin-2.10.0/lib/active_admin/application.rb:115:in `load!'
/usr/local/bundle/gems/activeadmin-2.10.0/lib/active_admin/application.rb:142:in `routes'
/usr/local/bundle/gems/activeadmin-2.10.0/lib/active_admin.rb:76:in `routes'
/loomio/config/routes.rb:36:in `block in <main>'
/usr/local/bundle/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/route_set.rb:427:in `instance_exec'
/usr/local/bundle/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/route_set.rb:427:in `eval_block'
/usr/local/bundle/gems/actionpack-6.1.4.6/lib/action_dispatch/routing/route_set.rb:409:in `draw'
/loomio/config/routes.rb:13:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:48:in `load'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:326:in `block in load'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:326:in `load'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/application/routes_reloader.rb:47:in `block in load_paths'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/application/routes_reloader.rb:47:in `each'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/application/routes_reloader.rb:47:in `load_paths'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/application/routes_reloader.rb:21:in `reload!'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/application/routes_reloader.rb:35:in `block in updater'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/file_update_checker.rb:83:in `execute'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/application/routes_reloader.rb:10:in `execute'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/application/finisher.rb:195:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/application.rb:391:in `initialize!'
/loomio/config/environment.rb:5:in `<main>'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/bootsnap-1.10.3/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.4.6/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/application.rb:367:in `require_environment!'
/usr/local/bundle/gems/railties-6.1.4.6/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sentry-ruby-core-5.1.0/lib/sentry/rake.rb:24:in `execute'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
PG::ConnectionBad: could not connect to server: Connection timed out
        Is the server running on host "172.20.0.2" and accepting
        TCP/IP connections on port 5432?
/usr/local/bundle/gems/pg-1.3.2/lib/pg/connection.rb:637:in `async_connect_or_reset'
/usr/local/bundle/gems/pg-1.3.2/lib/pg/connection.rb:706:in `new'
/usr/local/bundle/gems/pg-1.3.2/lib/pg.rb:69:in `connect'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/postgresql_adapter.rb:78:in `new_client'
/usr/local/bundle/gems/activerecord-6.1.4.6/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
```

**Comment by dariusk** [comment]
Here's what `docker-compose logs db` gives me:

```
loomio-db      | PostgreSQL init process complete; ready for start up.
loomio-db      | 
loomio-db      | 2022-03-13 22:39:09.497 UTC [1] LOG:  starting PostgreSQL 12.2 (Debian 12.2-2.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit
loomio-db      | 2022-03-13 22:39:09.498 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
loomio-db      | 2022-03-13 22:39:09.498 UTC [1] LOG:  listening on IPv6 address "::", port 5432
loomio-db      | 2022-03-13 22:39:09.499 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
loomio-db      | 2022-03-13 22:39:09.507 UTC [65] LOG:  database system was shut down at 2022-03-13 22:39:09 UTC
loomio-db      | 2022-03-13 22:39:09.510 UTC [1] LOG:  database system is ready to accept connections
```

**Comment by robguthrie** [comment]
Hi @dariusk did you ever get this sorted out. I've recently run through and setup another Loomio instance, and things worked well for me, so I don't believe it's a problem with the system defaults.

**Comment by dariusk** [comment]
@robguthrie Nope, I'm still stuck on this. I even tried updating to c448fab31a3d9c2197f7ba098b0cde061a2d5094 and got the same error. Any thoughts at all on what the issue could be?

**Comment by robguthrie** [comment]
would you mind, if you don't have any data yet.. trying again with a fresh clone of the repo?

**Comment by dariusk** [comment]
I'll give it a shot.

**Comment by dariusk** [comment]
It's working! Thank you!

**Comment by dariusk** [comment]
One minor issue, @robguthrie -- I had to do `User.first.update(is_admin: true)` because `User.last` was `loomiohelperbot` (id 2), whereas id 1 was my account, for some reason.

**Comment by robguthrie** [comment]
Fantastic!
Thanks for letting me know about the helper bot. I'm hoping to remove that
user entirely soon.
