### ISSUE TITLE
ActiveRecord::ConnectionNotEstablished: FATAL:  password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by ArthegaAsdweri** [loomio/loomio-deploy#92]
Hey guys,

I'm using the default installation of your repo on my local docker-setup before deploying it to my live server.

Both the app and the worker are restart-looping with:

ActiveRecord::ConnectionNotEstablished: FATAL:  password authentication failed for user "postgres"

I have not changed any of the default values in the .env file yet. Shouldn't it work with the default password "password" ?

installing the database results in the same error:

> docker-compose run app rake db:setup
```
Creating docker-compose-loomio_app_run ... done
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/usr/local/bundle/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/local/bundle/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/usr/local/bundle/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: previous definition of Socket was here
/loomio/config/initializers/sidekiq.rb:2: warning: Sidekiq's Delayed Extensions will be removed in Sidekiq 7.0
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
rake aborted!
ActiveRecord::ConnectionNotEstablished: FATAL:  password authentication failed for user "postgres"
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in `rescue in new_client'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:77:in `new_client'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_handling.rb:283:in `connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/model_schema.rb:380:in `table_exists?'
/usr/local/bundle/bundler/gems/custom_counter_cache-7a4ed2c70c6a/lib/custom_counter_cache/model.rb:46:in `update_counter_cache'
/loomio/app/models/membership.rb:51:in `<class:Membership>'
/loomio/app/models/membership.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:30:in `require'
/loomio/app/helpers/error_rescue_helper.rb:15:in `included'
/loomio/app/controllers/application_controller.rb:4:in `include'
/loomio/app/controllers/application_controller.rb:4:in `<class:ApplicationController>'
/loomio/app/controllers/application_controller.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:30:in `require'
/usr/local/bundle/gems/inherited_resources-1.13.1/app/controllers/inherited_resources/base.rb:11:in `<module:InheritedResources>'
/usr/local/bundle/gems/inherited_resources-1.13.1/app/controllers/inherited_resources/base.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:30:in `require'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/base_controller/authorization.rb:3:in `<module:ActiveAdmin>'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/base_controller/authorization.rb:2:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/base_controller.rb:2:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/resource_controller/action_builder.rb:3:in `<module:ActiveAdmin>'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/resource_controller/action_builder.rb:2:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/resource_controller.rb:3:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/batch_actions.rb:8:in `block in <main>'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin.rb:116:in `block in wrap_block_for_active_support_notifications'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications/fanout.rb:186:in `finish'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications/fanout.rb:63:in `block in finish'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications/fanout.rb:63:in `each'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications/fanout.rb:63:in `finish'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications/instrumenter.rb:45:in `finish_with_state'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications/instrumenter.rb:30:in `instrument'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications.rb:203:in `instrument'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/application.rb:115:in `load!'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/application.rb:142:in `routes'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin.rb:76:in `routes'
/loomio/config/routes.rb:36:in `block in <main>'
/usr/local/bundle/gems/actionpack-6.1.7.2/lib/action_dispatch/routing/route_set.rb:427:in `instance_exec'
/usr/local/bundle/gems/actionpack-6.1.7.2/lib/action_dispatch/routing/route_set.rb:427:in `eval_block'
/usr/local/bundle/gems/actionpack-6.1.7.2/lib/action_dispatch/routing/route_set.rb:409:in `draw'
/loomio/config/routes.rb:13:in `<main>'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:47:in `load'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:47:in `block in load_paths'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:47:in `each'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:47:in `load_paths'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:21:in `reload!'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:35:in `block in updater'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/file_update_checker.rb:83:in `execute'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:10:in `execute'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/finisher.rb:195:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application.rb:391:in `initialize!'
/loomio/config/environment.rb:5:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application.rb:367:in `require_environment!'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sentry-ruby-5.8.0/lib/sentry/rake.rb:24:in `execute'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'

Caused by:
PG::ConnectionBad: FATAL:  password authentication failed for user "postgres"
/usr/local/bundle/gems/pg-1.4.5/lib/pg/connection.rb:632:in `async_connect_or_reset'
/usr/local/bundle/gems/pg-1.4.5/lib/pg/connection.rb:760:in `connect_to_hosts'
/usr/local/bundle/gems/pg-1.4.5/lib/pg/connection.rb:695:in `new'
/usr/local/bundle/gems/pg-1.4.5/lib/pg.rb:69:in `connect'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:78:in `new_client'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/postgresql_adapter.rb:37:in `postgresql_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `public_send'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:882:in `new_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:926:in `checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:905:in `try_to_checkout_new_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:866:in `acquire_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:588:in `checkout'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:428:in `connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_adapters/abstract/connection_pool.rb:1128:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_handling.rb:327:in `retrieve_connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/connection_handling.rb:283:in `connection'
/usr/local/bundle/gems/activerecord-6.1.7.2/lib/active_record/model_schema.rb:380:in `table_exists?'
/usr/local/bundle/bundler/gems/custom_counter_cache-7a4ed2c70c6a/lib/custom_counter_cache/model.rb:46:in `update_counter_cache'
/loomio/app/models/membership.rb:51:in `<class:Membership>'
/loomio/app/models/membership.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:30:in `require'
/loomio/app/helpers/error_rescue_helper.rb:15:in `included'
/loomio/app/controllers/application_controller.rb:4:in `include'
/loomio/app/controllers/application_controller.rb:4:in `<class:ApplicationController>'
/loomio/app/controllers/application_controller.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:30:in `require'
/usr/local/bundle/gems/inherited_resources-1.13.1/app/controllers/inherited_resources/base.rb:11:in `<module:InheritedResources>'
/usr/local/bundle/gems/inherited_resources-1.13.1/app/controllers/inherited_resources/base.rb:1:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:30:in `require'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/base_controller/authorization.rb:3:in `<module:ActiveAdmin>'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/base_controller/authorization.rb:2:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/base_controller.rb:2:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/resource_controller/action_builder.rb:3:in `<module:ActiveAdmin>'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/resource_controller/action_builder.rb:2:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/resource_controller.rb:3:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/batch_actions.rb:8:in `block in <main>'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin.rb:116:in `block in wrap_block_for_active_support_notifications'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications/fanout.rb:186:in `finish'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications/fanout.rb:63:in `block in finish'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications/fanout.rb:63:in `each'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications/fanout.rb:63:in `finish'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications/instrumenter.rb:45:in `finish_with_state'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications/instrumenter.rb:30:in `instrument'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/notifications.rb:203:in `instrument'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/application.rb:115:in `load!'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin/application.rb:142:in `routes'
/usr/local/bundle/gems/activeadmin-2.13.1/lib/active_admin.rb:76:in `routes'
/loomio/config/routes.rb:36:in `block in <main>'
/usr/local/bundle/gems/actionpack-6.1.7.2/lib/action_dispatch/routing/route_set.rb:427:in `instance_exec'
/usr/local/bundle/gems/actionpack-6.1.7.2/lib/action_dispatch/routing/route_set.rb:427:in `eval_block'
/usr/local/bundle/gems/actionpack-6.1.7.2/lib/action_dispatch/routing/route_set.rb:409:in `draw'
/loomio/config/routes.rb:13:in `<main>'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:47:in `load'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:47:in `block in load_paths'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:47:in `each'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:47:in `load_paths'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:21:in `reload!'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:35:in `block in updater'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/file_update_checker.rb:83:in `execute'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/routes_reloader.rb:10:in `execute'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application/finisher.rb:195:in `block in <module:Finisher>'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `instance_exec'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/initializable.rb:32:in `run'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/initializable.rb:61:in `block in run_initializers'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/initializable.rb:60:in `run_initializers'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application.rb:391:in `initialize!'
/loomio/config/environment.rb:5:in `<main>'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
/usr/local/bundle/gems/zeitwerk-2.6.7/lib/zeitwerk/kernel.rb:38:in `require'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:332:in `block in require'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:299:in `load_dependency'
/usr/local/bundle/gems/activesupport-6.1.7.2/lib/active_support/dependencies.rb:332:in `require'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application.rb:367:in `require_environment!'
/usr/local/bundle/gems/railties-6.1.7.2/lib/rails/application.rb:533:in `block in run_tasks_blocks'
/usr/local/bundle/gems/sentry-ruby-5.8.0/lib/sentry/rake.rb:24:in `execute'
/usr/local/bundle/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
Tasks: TOP => db:setup => db:create => db:load_config => environment
(See full trace by running task with --trace)
ERROR: 1
```

**Comment by ArthegaAsdweri** [comment]
After logging into the postgres-DB and changing the password of the postgres user to "password" it works.
This should be stated somewhere in the documentation.

**Comment by robguthrie** [comment]
Oh thanks for letting me know, I changed the default database version - that must have changed the behaviour

**Comment by ArthegaAsdweri** [comment]
Can you verify that the actual compose-file works?

I just get a 502 - Bad Gateway from the nginx.
First I thought it would be due to the local environment - but now it's not running on production either - with a valid domain and smtp server.

**Comment by robguthrie** [comment]
Oh yea, absolutely. I set these up regularly, just pasting the instructions in the readme.

It will say bad gateway until the letsencrypt cert is issued and the rails server starts. What do your logs say?

**Comment by robguthrie** [comment]
I'll do a quick run through now and confirm

**Comment by robguthrie** [comment]
Ok. I just deleted my loomio-deploy folder, deleted all containers and volumes, and followed the instructions in the readme, no other commands at all. And now you can see it running here:

https://loomiotest.org

**Comment by ArthegaAsdweri** [comment]
app:
`[9] Puma starting in cluster mode...
[9] * Puma version: 6.1.0 (ruby 2.7.6-p219) ("The Way Up")
[9] *  Min threads: 12
[9] *  Max threads: 12
[9] *  Environment: production
[9] *   Master PID: 9
[9] *      Workers: 2
[9] *     Restarts: (✔) hot (✖) phased
[9] * Preloading application
/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/usr/local/bundle/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/local/bundle/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/usr/local/bundle/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: previous definition of Socket was here
/loomio/config/initializers/sidekiq.rb:2: warning: Sidekiq's Delayed Extensions will be removed in Sidekiq 7.0
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
[9] * Listening on http://0.0.0.0:3000
[9] Use Ctrl-C to stop
[9] - Worker 0 (PID: 12) booted in 0.01s, phase: 0
[9] - Worker 1 (PID: 26) booted in 0.01s, phase: 0`

worker:
`/usr/local/lib/ruby/2.7.0/net/protocol.rb:66: warning: already initialized constant Net::ProtocRetryError
/usr/local/bundle/gems/net-protocol-0.1.3/lib/net/protocol.rb:68: warning: previous definition of ProtocRetryError was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:206: warning: already initialized constant Net::BufferedIO::BUFSIZE
/usr/local/bundle/gems/net-protocol-0.1.3/lib/net/protocol.rb:208: warning: previous definition of BUFSIZE was here
/usr/local/lib/ruby/2.7.0/net/protocol.rb:503: warning: already initialized constant Net::NetPrivate::Socket
/usr/local/bundle/gems/net-protocol-0.1.3/lib/net/protocol.rb:504: warning: previous definition of Socket was here
/loomio/config/initializers/sidekiq.rb:2: warning: Sidekiq's Delayed Extensions will be removed in Sidekiq 7.0
`Redis#exists(key)` will return an Integer by default in redis-rb 4.3. The option to explicitly disable this behaviour via `Redis.exists_returns_integer` will be removed in 5.0. You should use `exists?` instead.
2023-02-24T13:28:38.555Z pid=10 tid=8a2 INFO: Booted Rails 6.1.7.2 application in production environment
2023-02-24T13:28:38.555Z pid=10 tid=8a2 INFO: Running in ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
2023-02-24T13:28:38.555Z pid=10 tid=8a2 INFO: See LICENSE and the LGPL-3.0 for licensing details.
2023-02-24T13:28:38.555Z pid=10 tid=8a2 INFO: Upgrade to Sidekiq Pro for more features and support: https://sidekiq.org`

redis:
`[...]
1:M 25 Feb 2023 10:58:40.013 * 100 changes in 300 seconds. Saving...
1:M 25 Feb 2023 10:58:40.014 * Background saving started by pid 277
277:C 25 Feb 2023 10:58:40.019 * DB saved on disk
277:C 25 Feb 2023 10:58:40.020 * RDB: 0 MB of memory used by copy-on-write
1:M 25 Feb 2023 10:58:40.115 * Background saving terminated with success`

db:
```
2023-02-24 13:23:57.610 UTC [110] ERROR:  database "loomio_production" already exists
2023-02-24 13:23:57.610 UTC [110] STATEMENT:  CREATE DATABASE "loomio_production" ENCODING = 'utf8'
2023-02-24 13:24:40.031 UTC [65] LOG:  checkpoint starting: time
2023-02-24 13:25:29.404 UTC [65] LOG:  checkpoint complete: wrote 490 buffers (3.0%); 1 WAL file(s) added, 0 removed, 0 recycled; write=49.193 s, sync=0.032 s, total=49.373 s; sync files=167, longest=0.004 s, average=0.001 s; distance=3844 kB, estimate=3844 kB
2023-02-24 13:29:40.503 UTC [65] LOG:  checkpoint starting: time
2023-02-24 13:29:42.340 UTC [65] LOG:  checkpoint complete: wrote 19 buffers (0.1%); 0 WAL file(s) added, 0 removed, 0 recycled; write=1.818 s, sync=0.007 s, total=1.838 s; sync files=6, longest=0.004 s, average=0.002 s; distance=63 kB, estimate=3466 kB
```

channels:
`> loomio_channel_server@0.0.1 start /app
> node --harmony index.js
Allowed origin https://consent.thrive-villages.com
booting bots!
bot redis connected`

mailin: (this one probably does not work because i have a mail server running on port 25 already)
```(node:8) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
info: Mailin v3.0.4
info: Webhook url: http://app:3000/email_processor/
info: Log file: /var/log/mailin.log
info: Spam score computation is disabled
(node:15) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
info: Mailin Smtp server listening on port 25
warn: Webhook http://app:3000/email_processor/ seems invalid or down. You may want to double check the webhook url.
```

Here is the domain:
https://consent.thrive-villages.com/

certificate issued - still not reaching the endpoint obviously.

**Comment by ArthegaAsdweri** [comment]
I just found out that it seems to be affected by the nginx-proxy. Since today is saturday I had the chance to shut down my other stack where the nginx-proxy runs normally.

Can you point me to the >relevant< difference between those two? 

mine:
```
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy/certs:/etc/nginx/certs/:ro
      - ./nginx-proxy/vhost:/etc/nginx/vhost.d
      - ./nginx-proxy/html:/usr/share/nginx/html/
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./config/nginx/proxy.conf:/etc/nginx/conf.d/custom.conf:ro
      - ./config/nginx/default_location.conf:/etc/nginx/vhost.d/default_location:ro
      - ./config/nginx/www.soul-empowerment.de.conf:/etc/nginx/vhost.d/www.soul-empowerment.de:ro
      - ./config/nginx/fvtt.hahn-webdesign.de.conf:/etc/nginx/vhost.d/fvtt.hahn-webdesign.de:ro
      - ./config/nginx/portainer.hahn-webdesign.de.conf:/etc/nginx/vhost.d/portainer.hahn-webdesign.de:ro
    environment:
      TZ: Europe/Berlin
```

yours:
```
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    networks:
      - main
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf:ro
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
```    

mine:
```
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: acme-companion
    restart: unless-stopped
    volumes:
      - ./nginx-proxy/html:/usr/share/nginx/html/
      - ./nginx-proxy/vhost:/etc/nginx/vhost.d/
      - ./nginx-proxy/certs:/etc/nginx/certs/:rw
      - ./nginx-proxy/acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: Europe/Berlin
      DEFAULT_EMAIL: admin@hahn-webdesign.de
      NGINX_PROXY_CONTAINER: nginx-proxy
```      

yours:
```
  nginx-proxy-acme:
    image: nginxproxy/acme-companion
    networks:
      - main
    depends_on:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    restart: unless-stopped
```

**Comment by robguthrie** [comment]
Sorry, are you using a custom docker compose? I'm not able to support custom configs, that's up to you. I've tested the provided code and it works well.

One thing to note is that you need to ensure the app container has a  VIRTUAL_HOST and LETSENCRYPT_HOST envs defined.
