### ISSUE TITLE
error on new install when setting up accounts

### ISSUE THREAD

**Issue by ariacomputer** [loomio/loomio-deploy#94]
I'm seeing the following error on a new Loomio instance when trying to set up a new user: 

```loomio-app                        | I, [2023-07-13T22:44:16.405476 #15]  INFO -- : [7358ffb0-f56c-45c4-b159-a99018354b10] method=POST path=/api/v1/registrations format=json controller=API::V1::RegistrationsController action=create status=500 duration=5998.94 view=0.00 db=74.00
loomio-app                        | F, [2023-07-13T22:44:16.407256 #15] FATAL -- : [7358ffb0-f56c-45c4-b159-a99018354b10]
loomio-app                        | [7358ffb0-f56c-45c4-b159-a99018354b10] SocketError (getaddrinfo: Name or service not known):
loomio-app                        | [7358ffb0-f56c-45c4-b159-a99018354b10]
loomio-app                        | [7358ffb0-f56c-45c4-b159-a99018354b10] app/services/login_token_service.rb:7:in `create'
loomio-app                        | [7358ffb0-f56c-45c4-b159-a99018354b10] app/controllers/api/v1/registrations_controller.rb:16:in `create'
loomio-app                        | [7358ffb0-f56c-45c4-b159-a99018354b10] app/helpers/locales_helper.rb:8:in `use_preferred_locale'
loomio-app                        | [7358ffb0-f56c-45c4-b159-a99018354b10] app/helpers/locales_helper.rb:3:in `process_time_zone'
loomio-app                        | I, [2023-07-13T22:44:16.410563 #15]  INFO -- : source=rack-timeout id=7358ffb0-f56c-45c4-b159-a99018354b10 timeout=15000ms service=6056ms state=completed```

**Comment by robguthrie** [comment]
Line 7 of login_token_service is where we try to deliver the login email.

I'd say you need to check your SMTP settings.
